from .auth_routes import auth_bp
from .user_routes import user_bp
from .guestbook_routes import guestbook_bp
from .event_routes import event_bp
from .admin import admin_bp
from .photo_routes import photo_bp
from .schedule_routes import schedule_bp
from .stats_routes import stats_bp
from .newsrookie_routes import newsrookie_bp
